=== RojalJoy/webstacklab/2347249 LabExercise4/amazon.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT products (product+)>
<!ELEMENT product (name,price,avail_qnty,category)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT avail_qnty (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ATTLIST product pid ID #REQUIRED>
<!ATTLIST product lang (Java|C|Python) "Java">

=== RojalJoy/webstacklab/2347249 LabExercise4/amazon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE products SYSTEM "amazon.dtd">
<products>
    <product pid="P1" lang="Java">
        <name>TV</name>
        <price>499.49</price>
        <avail_qnty>10</avail_qnty>
        <category>Electronics</category>
    </product>
    <product pid="P2" lang="Java">
        <name>Top</name>
        <price>10.99</price>
        <avail_qnty>100</avail_qnty>
        <category>Clothing</category>
    </product>
    <product pid="P3" lang="Java">
        <name>Webstack Devoplement</name>
        <price>15.66</price>
        <avail_qnty>200</avail_qnty>
        <category>Books</category>
    </product>
</products>
